name: 'cbc_analytics'
version: '1.0.0'
config-version: 2

profile: 'cbc_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  cbc_analytics:
    staging:
      +materialized: view
      +schema: staging
    intermediate:
      +materialized: view
      +schema: intermediate
    marts:
      +materialized: table
      +schema: marts
      session_analytics:
        +materialized: incremental
        +unique_key: session_id
        +on_schema_change: sync_all_columns
      faq_intelligence:
        +materialized: table
      service_operations:
        +materialized: table
      guest_preferences:
        +materialized: incremental
        +unique_key: guest_id

vars:
  # Retention periods
  event_retention_days: 365
  aggregate_retention_days: 730
  
  # SLA thresholds (in minutes)
  sla_thresholds:
    urgent: 15
    high: 60
    medium: 240
    low: 1440
  
  # Deflection calculation window
  deflection_window_minutes: 5