cbc_analytics:
  outputs:
    dev:
      type: postgres
      threads: 4
      host: "{{ env_var('DATABASE_HOST', 'localhost') }}"
      port: "{{ env_var('DATABASE_PORT', '5432') | int }}"
      user: "{{ env_var('DATABASE_USER', 'cbc') }}"
      pass: "{{ env_var('DATABASE_PASSWORD', 'cbc_analytics_2024') }}"
      dbname: "{{ env_var('DATABASE_NAME', 'cbc_analytics') }}"
      schema: public
      keepalives_idle: 30
      search_path: [public]
    prod:
      type: postgres
      threads: 8
      host: "{{ env_var('DATABASE_HOST') }}"
      port: "{{ env_var('DATABASE_PORT') | int }}"
      user: "{{ env_var('DATABASE_USER') }}"
      pass: "{{ env_var('DATABASE_PASSWORD') }}"
      dbname: "{{ env_var('DATABASE_NAME') }}"
      schema: public
      keepalives_idle: 30
      search_path: [public]
  target: dev